### ISSUE TITLE
Support sidebar colors based on Git status

### ISSUE THREAD

**Issue by chibicode** [atelierbram/Base2Tone-VSCode-Themes#1]
Hi there, great work on this theme! I was wondering if you'd be willing to consider supporting sidebar colors based on Git status. For example [this theme](https://github.com/uloco/theme-bluloco-light) uses green color for new file and blue color for modified file. It doesn't need to be green / blue - perhaps the first tone color for new file, the second tone color for modified file, and monotone color for other files might work.

<img width="216" alt="screen shot 2018-09-21 at 9 30 41 pm" src="https://user-images.githubusercontent.com/992008/45881291-b5cbe880-bde5-11e8-83e9-8b7c5903479b.png">

**Comment by atelierbram** [comment]
Thanks for the feedback; it proved to be helpful in clarifying some of my confusion and breaking the indecision on editing these sidebar colors. Just [updated the themes](https://github.com/atelierbram/Base2Tone-VSCode-Themes/commit/905314eb18995feacd6eadbbe8ef8b88b42598f3) : the default colors of sidebar list items are now monochrome to have the new - and modified files stand out more. 

Updating the theme and letting me know if these changes work for you (or not) will be appreciated.

**Comment by chibicode** [comment]
@atelierbram it looks excellent! I just added Base2Tone on my blog post: https://medium.com/@chibicode/the-best-visual-studio-code-dark-and-light-themes-july-2018-edition-a9c2cc9548da

**Comment by atelierbram** [comment]
Awesome, thanks for the recommendation!
