### ISSUE TITLE
editorSuggestWidget.highlightForeground was hard to read

### ISSUE THREAD

**Issue by chibicode** [atelierbram/Base2Tone-VSCode-Themes#2]
Hello again! I had to tweak `editorSuggestWidget.highlightForeground` when using the `Space Light` variant. As you can see, the highlighted text (`for`) is almost invisible.

<img width="365" alt="screen shot 2018-09-22 at 4 50 55 pm" src="https://user-images.githubusercontent.com/992008/45914990-0b58d180-be88-11e8-9618-2c3a2d18b943.png">

I fixed this by adding `"editorSuggestWidget.highlightForeground": "#dd672c"` (could be any darker color).

<img width="181" alt="screen shot 2018-09-22 at 4 54 27 pm" src="https://user-images.githubusercontent.com/992008/45915000-2fb4ae00-be88-11e8-8dff-541a52a831d0.png">

**Comment by atelierbram** [comment]
Hi there, thanks again for your feedback! Not having run in to this issue is revealing I guess .... Should be better now: fixed the selected background-color on dark themes as well.

**Comment by chibicode** [comment]
@atelierbram thank you!!
