### ISSUE TITLE
VSCode 1.24.1 version incompatibility 

### ISSUE THREAD

**Issue by aa-ya** [atelierbram/Base2Tone-VSCode-Themes#4]
I get an error when trying to install this theme from the extensions marketplace. I was also unable to manually install it with the `.vsix` file.

![image](https://user-images.githubusercontent.com/24833670/49343145-461e7900-f632-11e8-8137-552ab36fdc67.png)

**Comment by atelierbram** [comment]
@aa-ya Thanks for the feedback. Although the latest version of VSCode now is 1.29.1, and theme supported versions went back to 1.26.0 I did just set the compatibility back to a minimum VS Code version of 1.0.0. 
Could you maybe try to install the themes again, and let me know if this works or not?

**Comment by aa-ya** [comment]
It's working now. Thanks!
