### ISSUE TITLE
Fork Question

### ISSUE THREAD

**Issue by riotrah** [atelierbram/Base2Tone-VSCode-Themes#8]
Hi @atelierbram !

Love your work on this collection. I've read some of your writing on your color scheme designing process, end it's clear you've put quite a bit of thought into this - which I appreciate greatly.

Alas in my subjective opinion I find myself wanting to alter the light themes and little pieces here and there from the dark ones. 

I'd like to create a fork of this repo to create and share my variants. Is that alright with you? Would you prefer it to be named similarly, perhaps for unambiguous attribution, or would you prefer mine be named differently to create distance from yours? Any other considerations or objections?

Thanks again!

**Comment by atelierbram** [comment]
Just go ahead and keep the names the same for now in your fork, we can see about that later. Are you planning to use the [base16-builder](https://github.com/base16-builder/base16-builder) tool?

**Comment by riotrah** [comment]
I was just going to run `io.sh`, which appears to require the builer, so yes! Why do you ask?

**Comment by atelierbram** [comment]
OK cool, no specific reason, just interested.
